version: "3.7"
services:
  app:
    build:
      args:
        user: openagrosuser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: openagros
    container_name: openagros-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./_docker-compose/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - openagrosnetwork
  nginx:
    image: nginx:1.21-alpine
    container_name: openagros-nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./_docker-compose/nginx:/etc/nginx/conf.d
    networks:
      openagrosnetwork:
        aliases:
          - openagros.test
          - repl-imei.test
  db:
    image: timescale/timescaledb:latest-pg12
    container_name: openagros-timescale
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: openagros_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - 'openagrosdata:/var/lib/postgresql/data'
    networks:
      - openagrosnetwork
  pgadm:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - openagrosnetwork
networks:
  openagrosnetwork:
    driver: bridge
volumes:
  openagrosdata:
  pgadmin-data:
    driver: local

